# Execution Environment dependencies for the foundata.proxmox collection

---

version: 3

dependencies:
  galaxy:
    collections:
      "ansible.utils": ">=5.1.0"
      "ansible.posix": ">=2.0.0"
    roles: {}
